const CORE_SKILLS = [
  {
    desc: "I possess the skills to proficiently develop both the frontend and backend components of web applications, leveraging cutting-edge technologies such as React.js, Next.js, Node.js, Express.js, MongoDB, Firebase, and a range of other powerful tools.",
    icon: "https://www.svgrepo.com/show/261945/web-development.svg",
    priority: 1,
    title: "Web Development",
    _id: "Web_Development_2023-11-05-07:24:40",
  },
];

const TECHS = [
  {
    priority: 12,
    icon: "https://www.svgrepo.com/show/378440/nextjs-fill.svg",
    title: "Next.js",
    _id: "Next_js",
    proficiency: 90,
    level: "Expert",
    isFeatured: true,
  },
  {
    icon: "https://www.svgrepo.com/show/374032/reactjs.svg",
    _id: "React_js",
    priority: 11,
    title: "React.js",
    proficiency: 60,
    level: "Proficient",
    isFeatured: true,
  },
  {
    priority: 10,
    title: "Firebase",
    icon: "https://www.svgrepo.com/show/373595/firebase.svg",
    proficiency: 70,
    _id: "Firebase",
    level: "Advanced",
    isFeatured: true,
  },
  {
    proficiency: 30,
    icon: "https://www.svgrepo.com/show/373845/mongo.svg",
    priority: 9,
    _id: "MongoDB",
    title: "MongoDB",
    level: "Intermediate",
    isFeatured: true,
  },
  {
    proficiency: 50,
    icon: "https://www.svgrepo.com/show/354478/typescript-icon.svg",
    title: "TypeScript",
    priority: 8,
    _id: "TypeScript",
    level: "Proficient",
  },
  {
    proficiency: 79,
    title: "Node.js",
    _id: "Node_js",
    icon: "https://www.svgrepo.com/show/354119/nodejs-icon.svg",
    priority: 7,
    level: "Advanced",
  },
  {
    _id: "JavaScript",
    priority: 6,
    proficiency: 70,
    icon: "https://www.svgrepo.com/show/353925/javascript.svg",
    title: "JavaScript",
    level: "Advanced",
    isFeatured: true,
  },
  {
    icon: "https://www.svgrepo.com/show/374118/tailwind.svg",
    _id: "TailwindCSS",
    title: "TailwindCSS",
    priority: 5,
    proficiency: 80,
    level: "Advanced",
  },
  {
    proficiency: 50,
    title: "SASS/SCSS",
    _id: "SASS_SCSS",
    priority: 4,
    icon: "https://www.svgrepo.com/show/374067/scss2.svg",
    level: "Proficient",
  },
  {
    _id: "CSS",
    icon: "https://www.svgrepo.com/show/452185/css-3.svg",
    priority: 3,
    title: "CSS",
    proficiency: 60,
    level: "Proficient",
  },
  {
    icon: "https://www.svgrepo.com/show/452228/html-5.svg",
    _id: "HTML",
    proficiency: 70,
    title: "HTML",
    priority: 2,
    level: "Advanced",
  },
  {
    _id: "C",
    proficiency: 70,
    title: "C",
    priority: 1,
    icon: "https://www.svgrepo.com/show/373482/c.svg",
    level: "Advanced",
  },
];

const TOOLS = [
  {
    proficiency: "60",
    priority: 7,
    _id: "Express_js_2023-11-15-20:13:07",
    title: "Express.js",
    icon: "https://www.svgrepo.com/show/330398/express.svg",
    level: "Proficient",
  },
  {
    priority: 6,
    proficiency: "60",
    _id: "Vercel_2023-11-14-12:40:42",
    icon: "https://www.svgrepo.com/show/378475/vercel-fill.svg",
    title: "Vercel",
    level: "Proficient",
  },
  {
    priority: 5,
    title: "Axios",
    _id: "Axios_2023-11-14-12:39:41",
    icon: "https://www.svgrepo.com/show/452077/npm.svg",
    proficiency: "70",
    level: "Advanced",
  },
  {
    title: "Postman",
    _id: "Postman_2023-11-14-12:38:26",
    proficiency: "50",
    priority: 4,
    icon: "https://www.svgrepo.com/show/354202/postman-icon.svg",
    level: "Proficient",
  },
  {
    title: "Git",
    priority: 3,
    _id: "Git_2023-11-14-12:37:46",
    proficiency: "70",
    icon: "https://www.svgrepo.com/show/452210/git.svg",
    level: "Advanced",
  },
  {
    proficiency: "65",
    priority: 2,
    icon: "https://www.svgrepo.com/show/512317/github-142.svg",
    _id: "Github_2023-11-14-12:37:10",
    title: "Github",
    level: "Advanced",
  },
  {
    _id: "VS_Code_2023-11-05-07:35:05",
    title: "VS Code",
    icon: "https://www.svgrepo.com/show/452129/vs-code.svg",
    proficiency: 80,
    priority: 1,
    level: "Advanced",
  },
];

const SKILLS_JSON = {
  core: CORE_SKILLS,
  techs: TECHS,
  tools: TOOLS,
};

export default SKILLS_JSON;
