export const ICONS = {
  c: "https://www.svgrepo.com/show/373482/c.svg",
  css: "https://www.svgrepo.com/show/452185/css-3.svg",
  firebase: "https://www.svgrepo.com/show/373595/firebase.svg",
  html: "https://www.svgrepo.com/show/452228/html-5.svg",
  javascript: "https://www.svgrepo.com/show/353925/javascript.svg",
  mongodb: "https://www.svgrepo.com/show/373845/mongo.svg",
  next_js: "https://www.svgrepo.com/show/378440/nextjs-fill.svg",
  node_js: "https://www.svgrepo.com/show/452075/node-js.svg",
  react_js: "https://www.svgrepo.com/show/374032/reactjs.svg",
  tailwind_css: "https://www.svgrepo.com/show/374118/tailwind.svg",
  vite_js: "https://www.svgrepo.com/show/374167/vite.svg",
  web_development: "https://www.svgrepo.com/show/261945/web-development.svg",
  express_js: "https://www.svgrepo.com/show/330398/express.svg",
  framer_motion: "https://www.svgrepo.com/show/333088/framer.svg",
};
