import travellianImg from "@/assets/project-img/travellian.png";

const PROJECTS_JSON = [
  {
    img: "https://github.com/jrTilak/bumbleBee/raw/master/frontend/src/images/hero-image.png",
    sourceCode: "https://github.com/jrTilak/bumbleBee",
    techs: ["Express.js", "Mongodb", "Vite.js", "React.js", "Node.js"],
    liveDemo: "https://bumblebee.thapatilak.com.np/",
    type: "Website",
    title: "Bumblebee - AI Powered Chatbot",
    tags: ["react app", "jrtilak", "javascript", "vite", "chatbot"],
    desc: "Bumblebee is an AI powered chatbot that can help you with your queries. It is a web based application that can be accessed from anywhere. It is built using React.js, Express.js, MongoDB, and Vite.js. It uses OpenAI's GPT-3 API to generate responses to user queries.",
    _id: "Bumblebee_-_AI_Powered_Chatbot_2023-12-07-07:26:15",
    createdAt: "Jan 18, 2024",
    isFeatured: true,
  },
  {
    img: travellianImg,
    sourceCode: "https://github.com/jrTilak/travellian-frontend",
    techs: ["React.js", "Vite.js", "Tailwind CSS"],
    liveDemo: "https://travellian.thapatilak.com.np/",
    type: "Website",
    title: "Travellian - Travel Across the Globe",
    tags: ["nextjs", "jrtilak", "javascript", "tailwindcss", "webdev"],
    desc: "Travellian is a travel agency website that provides the best travel experience for your journey. It is built with Vite, React, and Tailwind CSS as a front-end internship project.",
    _id: "Travellian_-_Travel_Across_the_Globe_2023-12-07-07:26:15",
    createdAt: "Feb 1, 2024",
    isFeatured: true,
  },
  {
    img: "https://repository-images.githubusercontent.com/657066867/e4a5eeb3-de3e-4731-9db8-013a2e5c36af",
    sourceCode: "https://github.com/jrTilak/FSU",
    techs: ["Next.js", "Javascript", "CSS", "HTML"],
    liveDemo: "https://fsu.thapatilak.com.np/",
    type: "Website",
    title: "FSU - WebDev Competition",
    tags: ["nextjs", "jrtilak", "javascript", "tailwindcss", "webdev"],
    desc: "Welcome to the FSU Free Student Union IOE ERC Nepal website! This website has been developed as part of a web development competition using Next.js, React.js, Tailwind CSS, and Email.js, ensuring a seamless and responsive user experience.",
    _id: "FSU_-_WebDev_Competition_2023-12-07-07:26:15",
    createdAt: "Jun 28, 2023",
    isFeatured: true,
  },
  {
    type: "Website",
    techs: ["Vite.js", "React.js", "Node.js", "CSS", "HTML"],
    liveDemo: "https://stringify.thapatilak.com.np/",
    img: "https://repository-images.githubusercontent.com/652996745/de305753-89f8-42bb-87c1-9d6c06f19f70",
    desc: "Stringify is a user-friendly web app that simplifies text manipulation. With its intuitive interface, you can effortlessly perform tasks like case conversions, find and replace, URL encoding, and much more.",
    isFeatured: true,
    tags: ["react app", "jrtilak", "javascript", "vite", "text tools"],
    sourceCode: "https://github.com/jrTilak/Stringify",
    title: "Stringify - Effortless Text Manipulation",
    _id: "Stringify_-_Effortless_Text_Manipulation_2023-12-07-07:26:57",
    createdAt: "Jun 13, 2023",
  },
  {
    sourceCode: "https://github.com/jrTilak/C-Games",
    img: "https://repository-images.githubusercontent.com/665353287/ed3b74aa-ff46-4e5c-b34f-a5709d4f2f7d",
    desc: "C Games is a collection of interactive games developed as the 1st-semester project for the C programming subject at the IOE, Purwanchal Campus, Dharan. The program aims to provide a fun and engaging experience for users, allowing them to play various games. It also includes features like user account creation, login, game history tracking, and high-score recording.",
    title: "C Games - 1st sem Project",
    tags: ["c-language", "c projects", "jrtilak"],
    createdAt: "Jul 20, 2023",
    techs: ["C"],
    liveDemo: "https://github.com/jrTilak/C-Games",
    type: "CLI Game",
    _id: "C_Games_-_1st_sem_Project_2023-12-07-07:24:38",
  },
];

export default PROJECTS_JSON;
